### ISSUE TITLE
Similar project with tj-mode?

### ISSUE THREAD

**Issue by angelozerr** [jacksonrayhamilton/tern-context-coloring#1]
I tell me what is the difference with https://github.com/katspaugh/tj-mode ?

Perhaps you @katspaugh and @jacksonrayhamilton you could merge your project?

**Comment by jacksonrayhamilton** [comment]
`tj-mode` looks like an Emacs plugin with syntax highlighting and other goodies. This project will provide context-aware scope coloring only; see my [Emacs plugin](https://github.com/jacksonrayhamilton/context-coloring) for more info.

My initial reaction is that `tj-mode` is a "grab bag" of features, and tern-context-coloring could just as easily be a part of it as anything else; and since I prefer to keep things modular, that this plugin is better kept separate.

**Comment by jacksonrayhamilton** [comment]
Looks like @katspaugh agreed, so closing.
