### ISSUE TITLE
Request faild

### ISSUE THREAD

**Issue by fhdhsni** [jacksonrayhamilton/tern-context-coloring#2]
It says `Request faild: ((error http 400) . No query type 'context-coloring' defined`)
Any idea?

**Comment by jacksonrayhamilton** [comment]
Sounds like the Tern plugin isn't enabled. Have you installed `tern-context-coloring >= 1.0.0`, `tern >= 0.19`, and added `{"plugins": {"context-coloring": {"charOffset": 1}}}` to `~/.tern-config` or `/some/path/.tern-project`?

If there are still issues, please share your OS, Node, NPM, and Emacs versions, and any relevant configuration files.

**Comment by fhdhsni** [comment]
After updating to the latest version of `tern` (0.19) it gives me this new error
`Request faild: ((error connection-failed failed with code 111
  :host 127.0.0.1 :service 38483))`

tern itself works just fine.

[This](https://gist.github.com/fhdhsni/61191212fb864929e50fc889c8906596)  is the part of my init.el related to context-coloring and tern

and ~/.tern-config
`{
    "plugins": {
        "context-coloring": {
            "charOffset": 1,
            "blockScope": true
        }
    }
}`

I'm using `node v6.3.1`, `npm version 3.10.5` and GNU Emacs 24.5.1. My OS is Linux Manjaro (4.4.15-3-MANJARO)

**Comment by jacksonrayhamilton** [comment]
Regarding [this line](https://gist.github.com/fhdhsni/61191212fb864929e50fc889c8906596#file-init-el-L2):

> (add-to-list 'load-path "~/.node_modules_global/lib/node_modules/tern/emacs")
- Is that Tern also on the PATH? (What is the output of `ls -la $(which tern)`?)
- And does Emacs know about that Tern, too? (What is the output of `emacs -batch -eval '(message "%s" (executable-find "tern"))'`?)
- And is the `tern-context-coloring` npm package installed within `~/.node_modules_global/lib/node_modules/`?

**Comment by fhdhsni** [comment]
`» ls -la (which tern)`
`lrwxrwxrwx 1 farhad farhad 33 Aug  4 14:58 /home/farhad/.node_modules_global/bin/tern -> ../lib/node_modules/tern/bin/tern*`

`» emacs -batch -eval '(message "%s" (executable-find "tern"))
``/home/farhad/.node_modules_global/bin/tern`

`» ls ~/.node_modules_global/lib/node_modules/ | grep tern`
`tern`
`tern-context-coloring`

It still gives me the same error but (okay I wanna ask sth dumb) how can I see if it's working? your [context-coloring](https://github.com/jacksonrayhamilton/context-coloring) package already does the job of highlighting by scope. How tern-context-coloring would be different?

**Comment by jacksonrayhamilton** [comment]
Regarding the `code 111` error, I think that is an innocuous error that occurs when the Tern Emacs package tries to connect to a destroyed server due to a leftover `.tern-port` file in a project directory. If I run `revert-buffer` right afterwards, I don't see it again.

Regarding your PATH and installation directories, they all seem to be correct. I've also tried to recreate your environment as closely as possible, and `tern-context-coloring` integration seems to be working.

> your [context-coloring](https://github.com/jacksonrayhamilton/context-coloring) package already does the job of highlighting by scope. How tern-context-coloring would be different?

The `context-coloring` Emacs package can collect scope data from js2-mode. The `tern-context-coloring` Emacs package makes it possible to collect scope data from Tern instead.

AFAIK, Tern has a better understanding of scopes. For instance, if you enable the `node` plugin (`{"plugins": {"node": {}}}`) it knows that in Node.js, `module`, `exports` and `require` are free variables, not global variables (so they'd be colored as level 1 variables with `tern-context-coloring`, rather than as level 0 variables with `context-coloring` + `js2-mode`).

Not because of any shortcoming in `js2-mode` that I know about, but simply because I've given it more attention recently, `tern-context-coloring` is also a little more up-to-date with new ES features such as modules, arrow functions (`this`, `arguments` are colored like lexical variables) and object shorthand syntax (a key/value shorthand is colored like a lexical variable).

> how can I see if it's working?

Per the above the explanation, you can enable the `node` Tern plugin and visit a buffer with the following contents:

``` js
global;
require('foo');
```

If `global` and `require` are different colors, then `tern-context-coloring` is working.

**Comment by fhdhsni** [comment]
It works. 🙈
`global` is colored as level 0 and `require` is level 1.
You right. when I kill a buffer and open it again, or when I open another buffer that error doesn't show up.
Thank you so much for you thorough clarification, and thank you for this project.

**Comment by jacksonrayhamilton** [comment]
Glad to help. Maybe the `code 111` error should be reported to Tern; it's rather confusing.
