### ISSUE TITLE
Add a screenshot to the readme

### ISSUE THREAD

**Issue by Wilfred** [jacksonrayhamilton/tern-context-coloring#6]
I'd love to see a screenshot showing an example of JS code that benefits from this package.

**Comment by jacksonrayhamilton** [comment]
This package doesn't (really) do the coloring; it enhances a Tern server so that an editor plugin can do the coloring. I could copy over [the screenshot](https://github.com/jacksonrayhamilton/context-coloring/blob/master/screenshot.png) from the Emacs context coloring plugin, but I feel that would contradict the previous sentence, and make these packages look confusingly similar.

**Comment by Wilfred** [comment]
Fair enough :)

I simply assumed that context-coloring was just a library, so I just skimmed the .el file. I suppose you could link to the screenshot, but whatever suits you.
